# Generated by Django 3.1.7 on 2021-05-08 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionaria',
            fields=[
                ('identidad', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=12)),
                ('id_modulo', models.CharField(choices=[('MSSR', 'MSSR'), ('MEC', 'MEC'), ('MAPRODEM', 'MAPRODEM'), ('MAA', 'MAA'), ('MAI', 'MAI'), ('MAE', 'MAE'), ('DN', 'DN')], max_length=20)),
                ('identidad_funcionaria', models.CharField(default=None, max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Usuaria',
            fields=[
                ('identidad', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=12)),
                ('identidad_funcionaria', models.CharField(default=None, max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('temperatura1', models.CharField(choices=[('Mayor 37.5ºC', 'Mayor o igual a 37.5ºC'), ('Menor 37.5ºC', 'Menor o igual a 37.5ºC')], default=None, max_length=30, null=True)),
                ('id_funcionaria', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='triaje.funcionaria')),
                ('id_usuaria', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='triaje.usuaria')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(default=None, max_length=200, null=True)),
                ('id_funcionaria', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='triaje.funcionaria')),
                ('id_usuaria', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='triaje.usuaria')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.CharField(choices=[('Mayor 37.5ºC', 'Mayor o igual a 37.5ºC'), ('Menor 37.5ºC', 'Menor o igual a 37.5ºC')], max_length=30)),
                ('sintomas', models.CharField(default=None, max_length=500)),
                ('contacto', models.CharField(choices=[('Caso sospechoso de COVID-19', 'Caso sospechoso de COVID-19'), ('Caso confirmado de COVID-19', 'Caso confirmado de COVID-19'), ('Ninguna de las anteriores', 'Ninguna de las anteriores')], max_length=100)),
                ('id_funcionaria', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='triaje.funcionaria')),
                ('id_usuaria', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='triaje.usuaria')),
            ],
        ),
    ]
